Bundle 'an146/vundle'

Bundle 'tpope/vim-fugitive'
Bundle 'airblade/vim-rooter'
Bundle 'wincent/Command-T'
Bundle 'Rename'
Bundle 'snipMate'
Bundle 'SnipMgr'
Bundle 'taglist.vim'
Bundle 'SmartCase'
Bundle 'TeTrIs'
Bundle 'matrix.vim--Yang'
Bundle 'vim-coffee-script'

" Bundle 'oscarh/vimerl'
